baseurl = "http://www.yutanagano.com"
locale = 'en-us'
title = "Yuta Nagano"

[caches]
[caches.images]
dir = ':cacheDir/images'

[menu]
[[menu.main]]
name = "CV"
pageRef = "/cv"
[[menu.main]]
name = "Publications"
pageRef = "/publications"
[[menu.main]]
name = "Software"
pageRef = "/software"
[[menu.main]]
name = "Blog"
pageRef = "/blog"

[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]
